### ISSUE TITLE
GDAL_ERROR 6: Unable to load PROJ.4 library (libproj.so)

### ISSUE THREAD

**Issue by jordn** [dulaccc/heroku-buildpack-geodjango#1]
When using admin.OSMGeoAdmin as my ModelAdmin I get the following error when viewing a PointField in admin:

    GDAL_ERROR 6: Unable to load PROJ.4 library (libproj.so), creation of
    OGRCoordinateTransformation failed.
    Error transforming geometry from srid '4326' to srid '3857' (OGR failure.)

Looking around the heroku file system this file seems to be in this location fine `/app/.geodjango/proj4/lin/libproj.so`

I'm not sure how to debug any further.

**Comment by acer9997** [comment]
That fix worked for me also. I was getting an OGRException error, but only with Heroku. Running locally with "foreman start" or "manage.py runserver" didn't cause the error. Should probably look at making this a permanent fix.

**Comment by dulaccc** [comment]
Indeed @acer9997 I've included the fix in the buildpack, no need to do manual fixing.
