### ISSUE TITLE
GEOS not detected

### ISSUE THREAD

**Issue by fejoajam** [dulaccc/heroku-buildpack-geodjango#12]
I'm using GeoDjango buildpack for Heroku and keep having an issue that I can't solve and am going around in circles. I was hoping someone can help.

App seems to build ok:

Counting objects: 4, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 356 bytes | 0 bytes/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Fetching custom git buildpack... done
remote: -----> Python app detected
remote:        Using geos version: 3.4.2
remote:        Installed
remote:        GEOS installed and accessible with env variable 'GEOS_LIBRARY_PATH'
remote:        Using proj version: 4.8.0_1
remote:        Installed
remote:        Proj.4 installed and accessible with env variable 'PROJ4_LIBRARY_PATH'
remote:        Using gdal version: 1.11.1
remote:        Installed
remote:        GDAL installed and accessible with env variable 'GDAL_LIBRARY_PATH'
remote: -----> Installing dependencies with pip
remote: 
remote: -----> Preparing static assets
remote:        Collectstatic configuration error. To debug, run:
remote:        $ heroku run python manage.py collectstatic --noinput
remote: 
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote: 
remote: -----> Compressing... done, 141.3MB
remote: -----> Launching... done, v33

But the issue arrises when I change the model file and then try to run:
heroku run python manage.py makemigrations

I'm getting an error:
django.core.exceptions.ImproperlyConfigured: GEOS is required and has not been detected. Are you sure it is installed?

My settings file contains:
GEOS_LIBRARY_PATH = environ.get('GEOS_LIBRARY_PATH')
GDAL_LIBRARY_PATH = environ.get('GDAL_LIBRARY_PATH')

I’m relatively new to Django and Heroku, is there something obvious I’m doing wrong? I suspect it might be a path issue, but I'm not sure how to resolve it.

Many thanks

**Comment by dulaccc** [comment]
I would advise to use the excellent [https://github.com/cyberdelia/heroku-geo-buildpack](https://github.com/cyberdelia/heroku-geo-buildpack).

Better architectured, it uses the multi-buildpack feature brillantly.

I am considering deprecating my buildpack over this one. You might give it a change, I personally have moved my project to this other buildpack.

**Comment by dulaccc** [comment]
I've taken the decision to deprecate it, but I keep the repo for those who reference it.

Cheers
