### ISSUE TITLE
cedar-14 support

### ISSUE THREAD

**Issue by gadybadger** [dulaccc/heroku-buildpack-geodjango#3]
Any chance this fork will support cedar-14?

**Comment by dulaccc** [comment]
Did you manage to try against this bug ?

**Comment by gadybadger** [comment]
My initial tests to upgrade an existing app failed, so I'll need to do more, but haven't had the time to yet.

**Comment by dulaccc** [comment]
Thanks for the feedback, I'll keep the issue open then. Let me know when you get back on that.
Cheers

**Comment by acechase** [comment]
@dulaccc - I just updated to cedar-14 on my staging application and it worked like a charm for me.

FWIW, the exact version of geodango l used was:
```
$> cat .buildpacks 
https://github.com/dulaccc/heroku-buildpack-geodjango.git#59fde6ca21e8d612e4ee4ddd075c2e3cf5e9da90
# and for completeness, my runtime.txt...
$> cat runtime.txt 
python-2.7.8
```

**Comment by dulaccc** [comment]
The cedar-14 stack support has been brought with the mentionned e6d02f2 commit. Finally :)
Cheers
