### ISSUE TITLE
collectstatic broken?

### ISSUE THREAD

**Issue by maroux** [dulaccc/heroku-buildpack-geodjango#6]
It looks like Heroku's collect static is broken because the environment variables related to GEOS aren't being exported correctly during that step. Is this a known issue or is there a workaround?

**Comment by dulaccc** [comment]
`collectstatic` is working for me on a clean new heroku app... do you have a custom `collectstatic` step ?

**Comment by maroux** [comment]
Ah, never mind. I messed up and set `GDAL_LIBRARY_PATH=""` in Heroku config. Sorry about that.

**Comment by dulaccc** [comment]
Glad you've found the reason ! :)
Cheers
