### ISSUE TITLE
OGRException: OGR failure.

### ISSUE THREAD

**Issue by ywarezk** [dulaccc/heroku-buildpack-geodjango#9]
Hi,
I'm running Django version 1.5.11, and just updated my heroku to cedar-14. 
My .buildpack file looks like this: 
```
https://github.com/dulaccc/heroku-buildpack-geodjango.git#1.1
https://github.com/heroku/heroku-buildpack-python
https://github.com/gregburek/heroku-buildpack-pgbouncer.git#v0.3.2
```

And my runtime looks like this:
```
python-2.7.9
```
My enviroment variables looks like so:
GDAL_LIBRARY_PATH:           /app/.geodjango/gdal/lib/libgdal.so.1.18.1
GEOS_LIBRARY_PATH:           /app/.geodjango/geos/lib/libgeos_c.so.1.8.2

for some reason I get an exception that looks like this: 
```
2015-06-28T08:41:44.478804+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/gis/gdal/error.py", line 40, in check_err
2015-06-28T08:41:44.478806+00:00 app[web.1]:     raise e(msg)
2015-06-28T08:41:44.478807+00:00 app[web.1]: OGRException: OGR failure.
```

Did anyone else encounter this and maybe can help? 
Thanks in advance

**Comment by utkuturunc** [comment]
Try setting an environment variable GDAL_DATA to /app/.geodjango/gdal/share/gdal

**Comment by dulaccc** [comment]
Hi @ywarezk, you should NOT use this `heroku-buildpack-geodjango` with another python buildpack.

I explain why, I've patched up this project before heroku multi buildpack feature was stable, so I've extended the official `heroku-buildpack-python` to create this project. If you merge the two you'll get unexpected behaviors.

So two choices : 

1. specify the `.buildpacks` as :

```txt
https://github.com/dulaccc/heroku-buildpack-geodjango.git#1.1
https://github.com/gregburek/heroku-buildpack-pgbouncer.git#v0.3.2
```

2. or use the excellent [heroku-geo-buildpack](https://github.com/cyberdelia/heroku-geo-buildpack) :

```txt
https://github.com/cyberdelia/heroku-geo-buildpack.git#1.3
https://github.com/heroku/heroku-buildpack-python
https://github.com/gregburek/heroku-buildpack-pgbouncer.git#v0.3.2
```

I'll keep this issue open, in case I've mistaken the underlying issue.

Cheers

**Comment by 7wonders** [comment]
heroku config:add GDAL_DATA="/app/.geodjango/gdal/share/gdal" 

worked for me when I was getting

'''
GDAL_ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
'''

**Comment by dulaccc** [comment]
Heads up, you can give a try to this other buildpack [https://github.com/cyberdelia/heroku-geo-buildpack](https://github.com/cyberdelia/heroku-geo-buildpack). Very well architectured, to leverage the power of multi-buildpacks in the right way.

I will deprecate my own buildpack over his today btw.

Cheers
